### ISSUE TITLE
SDNE Error

### ISSUE THREAD

**Issue by jiangxiluning** [palash1992/GEM#19]
Hi, I want to try SDNE, but it gives me following error:
```
Using TensorFlow backend.
/Users/luning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
Num nodes: 34, num edges: 77
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne_utils.py:71: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(50, activation="relu", kernel_regularizer=<keras.reg...)`
  W_regularizer=Reg.l1_l2(l1=nu1, l2=nu2))(y[i])
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne_utils.py:71: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(15, activation="relu", kernel_regularizer=<keras.reg...)`
  W_regularizer=Reg.l1_l2(l1=nu1, l2=nu2))(y[i])
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne_utils.py:73: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(2, activation="relu", kernel_regularizer=<keras.reg...)`
  W_regularizer=Reg.l1_l2(l1=nu1, l2=nu2))(y[K - 1])
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne_utils.py:75: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("de...)`
  encoder = Model(input=x, output=y[K])
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne_utils.py:90: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(15, activation="relu", kernel_regularizer=<keras.reg...)`
  W_regularizer=Reg.l1_l2(l1=nu1, l2=nu2))(y_hat[i + 1])
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne_utils.py:90: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(50, activation="relu", kernel_regularizer=<keras.reg...)`
  W_regularizer=Reg.l1_l2(l1=nu1, l2=nu2))(y_hat[i + 1])
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne_utils.py:92: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(34, activation="relu", kernel_regularizer=<keras.reg...)`
  W_regularizer=Reg.l1_l2(l1=nu1, l2=nu2))(y_hat[1])
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne_utils.py:96: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=Tensor("de...)`
  decoder = Model(input=y, output=x_hat)
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne_utils.py:108: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("in..., outputs=[<tf.Tenso...)`
  autoencoder = Model(input=x, output=[x_hat, y])
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne.py:116: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  output_shape=lambda L: L[1])
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/keras/legacy/layers.py:456: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  name=name)
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne.py:119: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  output_shape=lambda L: L[1])
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne.py:122: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  output_shape=lambda L: L[1])
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne.py:148: UserWarning: Update your `Model` call to the Keras 2 API: `Model(inputs=Tensor("x_..., outputs=[<tf.Tenso...)`
  self._model = Model(input=x_in, output=[x_diff1, x_diff2, y_diff])
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne.py:161: UserWarning: The semantics of the Keras 2 argument  `steps_per_epoch` is not the same as the Keras 1 argument `samples_per_epoch`. `steps_per_epoch` is the number of batches to draw from the generator at each epoch. Update your method calls accordingly.
  verbose=1
/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne.py:161: UserWarning: Update your `fit_generator` call to the Keras 2 API: `fit_generator(generator=<generator..., verbose=1, steps_per_epoch=0, epochs=50)`
  verbose=1
Epoch 1/50
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/Users/luning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/Users/luning/.pyenv/versions/3.6.1/Python.framework/Versions/3.6/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/keras/engine/training.py", line 606, in data_generator_task
    generator_output = next(self._generator)
  File "/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne_utils.py", line 50, in batch_generator_sdne
    deg_i = np.sum(X_batch_v_i != 0, 1).reshape((batch_size, 1))
ValueError: cannot reshape array of size 154 into shape (500,1)

Traceback (most recent call last):
  File "test.py", line 41, in <module>
    Y, t = embedding.learn_embedding(graph=G, edge_f=None, is_weighted=True, no_python=True)
  File "/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/embedding/sdne.py", line 161, in learn_embedding
    verbose=1
  File "/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/keras/legacy/interfaces.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/Users/luning/.pyenv/versions/3.6.1/envs/neo4j-demo/lib/python3.6/site-packages/keras/engine/training.py", line 1913, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
UnboundLocalError: local variable 'epoch_logs' referenced before assignment
```

**Comment by palash1992** [comment]
I believe the new Tensorflow doesn't allow batch size to be bigger than the number of data points. Try setting the batch size (n_batch in sdne.py) to 100

**Comment by jiangxiluning** [comment]
yep, the batch size is larger than the sample size, so cause the error shows. After I decreased the batch size, it ran normally.
