### ISSUE TITLE
Test script gives error when executed on karate edgelist

### ISSUE THREAD

**Issue by dionman** [palash1992/GEM#21]
Hello,

replacing the input dataset in the test script with the karate edgelist, I can the following error upon execution:

python test.py 
```
Using TensorFlow backend.
Couldn't import dot_parser, loading of dot files will not be possible.
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    models.append(GraphFactorization(2, 50000, 1*10**-4, 1.0))
  File "/code/GEM/gem/embedding/gf.py", line 44, in __init__
    for key in dictionary:
TypeError: 'int' object is not iterable
```

**Comment by palash1992** [comment]
The issue has now been fixed
