### ISSUE TITLE
Exception: ./node2vec not found. Please compile snap, place node2vec in the path and grant executable permission

### ISSUE THREAD

**Issue by caijiangyao1991** [palash1992/GEM#33]
i run node2vec in win10, python3.6 and got a problem , i don't know what's mean , i run it as the example you give. hope you can help me 

Traceback (most recent call last):
  File "D:\Anaconda\lib\site-packages\gem-1.0.0-py3.6.egg\gem\embedding\node2vec.py", line 80, in learn_embedding
    call(args)
  File "D:\Anaconda\lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "D:\Anaconda\lib\subprocess.py", line 709, in __init__
    restore_signals, start_new_session)
  File "D:\Anaconda\lib\subprocess.py", line 997, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] 系统找不到指定的文件。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "F:/project/network/networkEmbedding/node2vec.py", line 20, in <module>
    Y, t = embedding.learn_embedding(graph=G, is_weighted=True)
  File "D:\Anaconda\lib\site-packages\gem-1.0.0-py3.6.egg\gem\embedding\node2vec.py", line 83, in learn_embedding
    raise Exception('./node2vec not found. Please compile snap, place node2vec in the path and grant executable permission')
Exception: ./node2vec not found. Please compile snap, place node2vec in the path and grant executable permission

**Comment by palash1992** [comment]
Please read the readme.txt in c_exe folder.  For convenience I have put the content here:
1. Recompile from https://github.com/snap-stanford/snap and copy node2vec executable to this folder
2. To grant executable permission, run: chmod +x ./c_exe/node2vec

**Comment by caijiangyao1991** [comment]
hi palash , thanks for your answer but SANP need to compile in python2.7  , mine is python 3.6 ,is that mean i can't use your program? or how can i fix this problem

**Comment by palash1992** [comment]
Use the C++ version of SNAP which doesn't depend on the version of Python

**Comment by GittiHab** [comment]
Can't this be automated in the `setup.py` file?
