### ISSUE TITLE
AttributeError: 'DiGraph' object has no attribute '_node'

### ISSUE THREAD

**Issue by hurun** [palash1992/GEM#41]
python3.6, run exampl2 
error here

Traceback (most recent call last):
  File "C:/Users/hurun/PycharmProjects/GEM/Example1.py", line 47, in <module>
    print ('Num nodes: %d, num edges: %d' % (G.number_of_nodes(), G.number_of_edges()))
  File "C:\Users\hurun\AppData\Local\Programs\Python\Python36\lib\site-packages\networkx\classes\graph.py", line 780, in number_of_nodes
    return len(self._node)
AttributeError: 'DiGraph' object has no attribute '_node'

**Comment by palash1992** [comment]
Which version of networkx do you have? You need networkx 1.11 for it to work

**Comment by hurun** [comment]
> Which version of networkx do you have? You need networkx 1.11 for it to work

Thanks for your reply,fix error now
