### ISSUE TITLE
TypeError: unsupported operand type(s) for -: 'dict' and 'float'

### ISSUE THREAD

**Issue by hurun** [palash1992/GEM#42]
Traceback (most recent call last):
  File "C:/Users/hurun/PycharmProjects/GEM/Example1.py", line 52, in <module>
    Y, t = embedding.learn_embedding(graph=G, edge_f=None, is_weighted=True, no_python=True)
  File "C:\Users\hurun\AppData\Local\Programs\Python\Python36\lib\site-packages\gem-1.0.0-py3.6.egg\gem\embedding\gf.py", line 98, in learn_embedding
    [f1, f2, f] = self._get_f_value(graph)
  File "C:\Users\hurun\AppData\Local\Programs\Python\Python36\lib\site-packages\gem-1.0.0-py3.6.egg\gem\embedding\gf.py", line 56, in _get_f_value
    f1 += (w - np.dot(self._X[i, :], self._X[j, :]))**2
TypeError: unsupported operand type(s) for -: 'dict' and 'float'

**Comment by palash1992** [comment]
Fixing the _node error might take care of this. Let me know if it doesn't. You can also try printing out self._X[i, :] and self._X[j, :] to understand what is it taking as dictionary. I have never seen this issue before so it might be something system specific as well.

**Comment by hurun** [comment]
> Fixing the _node error might take care of this. Let me know if it doesn't. You can also try printing out self._X[i, :] and self._X[j, :] to understand what is it taking as dictionary. I have never seen this issue before so it might be something system specific as well.

Many Thanks , fix it now
