### ISSUE TITLE
meet an error when load embedding 

### ISSUE THREAD

**Issue by zuozijiZHOULI** [palash1992/GEM#49]
Traceback (most recent call last):
  File "test_karate.py", line 58, in <module>
    MAP, prec_curv = lp.evaluateStaticLinkPrediction(G,embedding)
  File "/home/public/anaconda3/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/evaluation/evaluate_link_prediction.py", line 47, in evaluateStaticLinkPrediction
    X=graph_util.loadEmbedding('data/node_vectors1.txt')
  File "/home/public/anaconda3/lib/python3.6/site-packages/gem-1.0.0-py3.6.egg/gem/utils/graph_util.py", line 191, in loadEmbedding
    X[int(emb[0]), :] = emb_fl
IndexError: index 469 is out of bounds for axis 0 with size 439

**Comment by palash1992** [comment]
Again, is_unidirected should be False.
