### ISSUE TITLE
Error when running link prediction

### ISSUE THREAD

**Issue by agoodweathercc** [palash1992/GEM#53]
When I try to run link prediction by adding the following code in test_karate.py
   
MAP, prec_curv = lp.evaluateStaticLinkPrediction(G, embedding, 0.8, is_undirected=False)

I got the error:
Traceback (most recent call last):
  File "tests/test_karate.py", line 55, in <module>
    MAP, prec_curv = lp.evaluateStaticLinkPrediction(G, embedding, 0.8, is_undirected=False)
  File "/home/cai.507/Documents/DeepLearning/deep-persistence/pythoncode/GEM/gem/evaluation/evaluate_link_prediction.py", line 24, in evaluateStaticLinkPrediction
    is_undirected=is_undirected
  File "/home/cai.507/Documents/DeepLearning/deep-persistence/pythoncode/GEM/gem/utils/evaluation_util.py", line 40, in splitDiGraphToTrainTest
    for (st, ed, w) in di_graph.edges_iter(data='weight', default=1):
AttributeError: 'DiGraph' object has no attribute 'edges_iter'

**Comment by agoodweathercc** [comment]
Would it be possible for you to provide a small example of link prediction and node classification? May thanks!

**Comment by palash1992** [comment]
You addition of code is correct but I believe you are using a version of Networkx incompatible with GEM. Please downgrade your Network to 1.x and let me know if that solves the issue.
