### ISSUE TITLE
running TypeError test_karate.py

### ISSUE THREAD

**Issue by louiseGAN514** [palash1992/GEM#54]
Hi,

I'd like to ask for help when re-running test_karate.py. An TypeError occurred like this:

> Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_bundle/pydev_umd.py", line 197, in runfile
    pydev_imports.execfile(filename, global_vars, local_vars)  # execute the script
  File "/Applications/PyCharm.app/Contents/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/lugan/PycharmProjects/GEM/tests/test_karate.py", line 47, in <module>
    Y, t = embedding.learn_embedding(graph=G, edge_f=None, is_weighted=True, no_python=True)
  File "/Users/lugan/PycharmProjects/GEM/gem/embedding/sdne.py", line 115, in learn_embedding
    output_shape=lambda L: L[1])
TypeError: 'module' object is not callable

It seems like merge doesn't exist in keras 2.* anymore. I am not sure if it's keras' version that causes the problem. (By the way, my Keras version is 2.2.4). Thanks a lot.

**Comment by palash1992** [comment]
As mentioned in the Readme, keras version should be 2.0.2. As they removed merge in newer version this part of the code is not compatible with newer keras versions.
